### ISSUE TITLE
Proposal for JSON Feed version 1.1

### ISSUE THREAD

**Issue by manton** [manton/JSONFeed#126]
There was a lot of great feedback on JSON Feed. It's time to update the spec to incorporate a few suggestions. We're thinking this will be a minor update, version 1.1.

* New type `application/feed+json` (#32). When discovering the feed, apps should still fall back to looking for `application/json` if nothing else more specific is present.
* Multiple `authors` (#6). Allow an array of authors instead of just one wherever we had a single `author` before.
* Add `language` (#62). This can be a top-level default or specified on each item.
* Update link to more recent version of JSON spec (#53).
* Clarify that `id` should really be a string (#60). Move the tip about gracefully handling a number to the "suggestions for feed readers" section and not in the main part of the spec to avoid confusion.

Anything else that should be included? Thanks!

**Comment by letrastudio** [comment]
I just posted #127, suggesting a `via_url` property for feed items.

> If `url` links to where you’re talking about a thing, and `external_url` links to the thing you’re talking about, then `via_url` links to where you heard about it.

Via links are a well-established pattern used in many blogs ([I use them myself](https://letra.studio/links/)). They're great for discovering new blogs or people to follow. Making them part of the spec might help make the idea even more popular, and could enable special handling of those links in feed readers.

**Comment by jameysharp** [comment]
I'd love to see #129 (which I just opened) addressed in a new version of this spec.

After filing that I found #100 which brought this up a couple years ago and was closed recently. The existing `next_url` attribute is the bare minimum so I'd like to see some more consideration given to this.

**Comment by manton** [comment]
I've posted a draft of version 1.1 here: https://github.com/manton/JSONFeed/blob/master/pages/version/1.1.markdown

**Comment by fboes** [comment]
I really like the new 1.1 draft, as it does not break backwards compability but for deprecating `author`, and adds `language` which I dearly missed.

Does the `version` property need to change for 1.1? Currently it still says `https://jsonfeed.org/version/1` in the 1.1 spec.

As for more feature requests, I propose to wait for later versions to incorporate these, so the changes in 1.1 do not get blocked waiting for more features.

**Comment by dshanske** [comment]
Can we see about pushing this for the mime type alone?

**Comment by manton** [comment]
Thanks y'all. Yes, it's time. I'm pushing the last tweaks.

**Comment by fboes** [comment]
Couldn't wait any longer… https://journal.3960.org/feed.json 😁

**Comment by Wevah** [comment]
Is there/should there be a custom UTI (maybe `org.jsonfeed.feed`)? (Related to that, should `json` be the recommended extension?)

**Comment by tedder** [comment]
So are you explicitly forking this, or is there hope @brentsimmons will update and/or add maintainers and keep this as the canonical repo?

**Comment by brentsimmons** [comment]
We will be updating the spec. We’re just slightly overwhelmed by other things at the moment, and we appreciate your patience.

**Comment by manton** [comment]
The web site has now been updated for version 1.1. Thanks everyone!
