### ISSUE TITLE
Confusing URL of “Announcing JSON Feed”

### ISSUE THREAD

**Issue by sonicdoe** [manton/JSONFeed#142]
The “Announcing JSON Feed” blog post is currently at [/2020/05/21/announcing-json-feed.html](https://www.jsonfeed.org/2020/05/21/announcing-json-feed.html). Previously, it was at [/2017/05/17/announcing_json_feed](https://jsonfeed.org/2017/05/17/announcing_json_feed). Given that the post was published on 17 May 2017—not 21 May 2020—the current URL looks confusing.

**Comment by manton** [comment]
Thanks, it must've accidentally changed while migrating the blog. I'll fix it.

**Comment by manton** [comment]
Fixed now. Thanks again.
