### ISSUE TITLE
https://validator.jsonfeed.org/ does not support v1.1 specification

### ISSUE THREAD

**Issue by xoxys** [manton/JSONFeed#143]
Looks like https://validator.jsonfeed.org does not support the latest specification. I got the following errors:

https://validator.jsonfeed.org/?url=https%3A%2F%2Fhugo-geekblog.geekdocs.de%2Ffeed.json

**Comment by manton** [comment]
Thanks, you're right. There's an updated schema that I think we can use to update the validator.

**Comment by j-f1** [comment]
I submitted a JSON Feed v1.1 schema to SchemaStore here: https://github.com/SchemaStore/schemastore/pull/1222. Feel free to comment if I should change anything, and to use it when it’s merged!

**Comment by xoxys** [comment]
@manton @j-f1 The PR seems to be merged. Could it be added to validator?

**Comment by uncenter** [comment]
The validator now has support for the latest `v1.1` spec. This can be closed!

**Comment by manton** [comment]
Thanks! Closing.
