### ISSUE TITLE
jsonfeed.org/graphics/icon.png not found

### ISSUE THREAD

**Issue by aslakr** [manton/JSONFeed#152]
From https://jsonfeed.org/version/1.1

```html
<div class="feedicon"><a 
href="https://jsonfeed.org/feed.json"><img 
src="https://jsonfeed.org/graphics/icon.png" /></a></div>
```

https://jsonfeed.org/graphics/icon.png -> 404 Not Found

**Comment by icy-comet** [comment]
> You can also use the JSON Feed icon as a link on your site, like this:
 `<div class="feedicon"><a href="https://jsonfeed.org/feed.json"><img src="https://jsonfeed.org/graphics/icon.png" /></a></div>`

yes indeed. the icon's [source URL](https://jsonfeed.org/graphics/icon.png) is returning a 404.

**Comment by manton** [comment]
Thanks, I've added a redirect to support that URL.
