### ISSUE TITLE
Reference to obsolete version of JSON spec

### ISSUE THREAD

**Issue by NorbertLindenberg** [manton/JSONFeed#53]
The JSON Feed specification contains the text "legal JSON" with a link to
https://www.ietf.org/rfc/rfc4627.txt
RFC 4627 is obsolete; the current JSON specification is RFC 7159:
https://tools.ietf.org/html/rfc7159

Note that it's generally better to reference RFCs by linking to their HTML versions, as those get annotated when they get obsoleted, e.g.:
https://tools.ietf.org/html/rfc4627

**Comment by manton** [comment]
Thanks, we've updated this for 1.1 of the spec.
